# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: appleblog_development
test:
  <<: *default
  database: appleblog_test
production:
  <<: *default
  database: appleblog
  username: root
  password:
